FROM datadog/agent:7

RUN printenv
RUN echo $HOSTNAME
RUN echo $HOME
RUN echo $DISPLAY

ENV DD_APM_ENABLED=true
ENV NON_LOCAL_TRAFFIC=true
ENV DD_APM_NON_LOCAL_TRAFFIC=true
ENV DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true

ARG DD_API_KEY
